name: Auth-Actions

on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-latest
    container: node:18

    outputs:
      output-1: ${{ steps.one.outputs.throw }}

    steps:
      - name: step1
        id: one
        run: echo "throw=Throwing from step-1" >> $GITHUB_OUTPUT

  consumer:
    runs-on: ubuntu-latest
    needs: producer

    outputs:
      output-c1: ${{ steps.c1.outputs.catch }}

    steps:
      - name: consumer
        id: c1
        run: |
          echo "The value received: ${{ needs.producer.outputs.output-1 }}"
          echo "catch=${{ needs.producer.outputs.output-1 }}" >> $GITHUB_OUTPUT

          
