name: Auth-Actions

on:
  workflow_dispatch:

env:
  hardcoded_data: data 

jobs:
  producer:
    runs-on: ubuntu-latest
    container: node:18

    outputs:
      output-1: ${{ steps.one.outputs.throw }}

    steps:
      - name: step1
        id: one
        run: echo "throw=Throwing from step-1" >> $GITHUB_OUTPUT

  consumer:
    runs-on: ubuntu-latest
    needs: producer

    outputs:
      output-c1: ${{ steps.c1.outputs.catch }}

    steps:
      - name: consumer
        id: c1
        run: |
          echo "The value received: ${{ needs.producer.outputs.output-1 }}"
          echo "catch=${{ needs.producer.outputs.output-1 }}" >> $GITHUB_OUTPUT

  randomJob:
    runs-on: ubuntu-latest
    needs: [consumer , producer]
    env:  
      my_secret: ${{secrets.MY_SECRET}}
      my_variable: ${{vars.MY_VARIABLE}}
    steps:
     - name: first-step
       id: first
       run: echo "Your secret variable is $my_secret"         

     - name: sec-step
       id: sec 
       run: echo "Your varibale is $my_variable"

     - name: third-step
       id: third 
       run: echo "Your global evn variable is $hardcoded_data"


  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy Job"
  dummy-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy Job"

  dummy-three:
    runs-on:  ubuntu-latest
    steps:
      - run: echo "Dummy job 3"